### ISSUE TITLE
[Error]: achievement_add: Achievement 240007 not found in DB.

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#2992]
* **rAthena Hash**: c1b9ee86940ad280af43b818d1b29218c40a26d9

* **Client Date**: 20170125.Ragexe

* **Server Mode**: Pre-renewal

* **Description of Issue**:  achievement_add: Achievement 240007 not found in DB.
  * Result:
  * Expected Result: There's should no 240007 after deleting all inside the achievement_db.yml
  * How to Reproduce: Delete all the default achievements, and add this one
```
Server Side:

  - ID: 400001
    Group: "AG_BATTLE"
    Name: "Monster of the Sand"
    Target:
      - MobID: 1159
        Count: 10
    Reward:
       ItemID: 32609
       Amount: 10
    Score: 50
```
```
Client Side:

	[400001] = {
		UI_Type = 0,
		group = "BATTLE",
		major = 5,
		minor = 0,
		title = "Monster of the Sand.",
		content = {
			summary = "Kill the monster of the Sand.",
			details = "Find the monster Phreeoni and kill it 10x."
		},
		resource = { [1] = { text = "Find the monster Phreeoni and kill it." } },
		reward = { item = 32609 },
		score = 50
	},
```
Complete the achievement and error in map server will show up.
  * Official Information:
  

* **Modifications that may affect results**:
