### ISSUE TITLE
Pet egg as mail attachment

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4327]
* **rAthena Hash**: a03d80e9b61ceb84851faa0853ac2893e4dcaae3

* **Client Date**: No applicable

* **Server Mode**: Pre Renewal

* **Description of Issue**: Making egg as achievement reward shows error in map-server.
  * Result:  `[Error]: wrong egg item inventory 25`
```
  - ID: 250007
    Group: "AG_BATTLE"
    Name: "Atroce The Warewolf"
    Target:
      - Id: 0
        MobID: 1785
        Count: 10
    Reward:
      ItemID: 40001 // Egg ID
      TitleID: 1040
    Score: 10
```
  * Expected Result: 
  * How to Reproduce: Add egg item as reward.
  * Official Information:
  

* **Modifications that may affect results**:
