### ISSUE TITLE
Feint Knockback Issue After Level 3

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4631]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/47131b4585d97ef93e50b6af13b6074c29a8f600

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: SC_FEINTBOMB knockback coded till level 3
  * Result:  Level 4 till level 10 theres no knockback
  * Expected Result: Increases travel distance depends on skill level. (Sorry, I dont have the data, anyone does ?)
  * How to Reproduce: Ive check the skill_db.yml 
```
    Knockback:
      - Level: 1
        Amount: 3
      - Level: 2
        Amount: 6
      - Level: 3
        Amount: 9
```
