### ISSUE TITLE
@reloadquestdb with a spacing error in quest_db.yml wipes online player quests

### ISSUE THREAD

**Issue by Latiosu** [rathena/rathena#4849]
* **rAthena Hash**: 05ebde019
* **Client Date**: 20180620
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Reloading quest database in-game with `@reloadquestdb` when you have a spacing error in `quest_db.yml` will cause all online player quests to be wiped from database.
  * Expected Result: `@reloadquestdb` should report a failure and online player quests should remain unchanged.
  * How to Reproduce:
    1. Over-indent once an quest entry set in `db/re/quest_db.yml` (ID line normally indented 2 spaces, now at 4 spaces). See example at end of issue.
    2. Save changes.
    3. Run `@reloadquestdb` command in-game.
    4. All online player quests are reported as "Deleted from quest log" and wiped from database.

  * Official Information: Not applicable

* **Modifications that may affect results**: I have not tested with other amounts of spaces the result may be different.

* **Other notes:** I think the mistake by the user should be more forgiving, perhaps if there is YAML validation that happens during the `@reloadquestdb` command it may catch the mistake before it actually happens.

* **Indentation error example**:

**Before (correct)**
```
  - Id: 60443
      Title: Alarm Hunting
      Targets:
      - Mob: ALARM
          Count: 400
```
**After (incorrect)**
```
    - Id: 60443
        Title: Alarm Hunting
        Targets:
        - Mob: ALARM
            Count: 400
```
