### ISSUE TITLE
About Item Trade

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5481]
* **rAthena Hash**: after item db convert to YAML

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: sorry beforehand, I don't think this is an issue. I just want to ask how the item trade is implemented? because it is now one with the item_db.yml. For example, I want the item database to remain official, for example red potion, but I want to change the item_trade only. do I have to copy all the red potion information to import? 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
You only need to write the `Id` of the item and your changes on import when you want to change the datas of an existing item. All previous datas are kept, import allow to remove/change/add new datas.

**Comment by Lemongrass3110** [comment]
Please ask questions like this in the forum or on discord in the support channel.

If you want to change red potion for example:
```
  - Id: 501
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      NoSell: true
      NoCart: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
```
