### ISSUE TITLE
update item Toughen_Metal_Mace

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5587]
* **rAthena Hash**: 9eeeb09ff61e84ab10935af905bc0a340f21e1ed

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: https://www.divine-pride.net/database/item/16054
``````
  - Id: 16054
    AegisName: Toughen_Metal_Mace
    Name: Enhanced Metal Mace
    Type: Weapon
    SubType: Mace
    Buy: 20
    Attack: 105
    Range: 1
    Slots: 1
    Jobs:
      Acolyte: true
      Archer: true
      Blacksmith: true
      Crusader: true
      Novice: true
      SuperNovice: true
      StarGladiator: true
      Thief: true
      Wizard: true
    Locations:
      Right_Hand: true
    WeaponLevel: 3
    EquipLevelMin: 100
    Refineable: true
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      NoCart: true
      NoStorage: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      bonus2 bSkillAtk,"GN_CARTCANNON",10;
      bonus2 bSkillAtk,"SR_SKYNETBLOW",10;
      bonus bBaseAtk,7*(getrefine()+(min(BaseLevel,150)/10));
``````
  * Result: 
  * Expected Result:  `remove jobs archer, thief and wizard`
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:
