### ISSUE TITLE
update item RWC_Memory_Mace

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5595]
* **rAthena Hash**: 495769036aa3dbddf0c3a6fc8f611822b6064382

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: https://www.divine-pride.net/database/item/16026
``````
  - Id: 16026
    AegisName: RWC_Memory_Mace
    Name: RWC Memory Mace
    Type: Weapon
    SubType: Mace
    Buy: 20
    Weight: 800
    Attack: 100
    Range: 1
    Slots: 1
    Jobs:
      Acolyte: true
      Alchemist: true
      Blacksmith: true
      Crusader: true
      Knight: true
      Merchant: true
      Monk: true
      Priest: true
      Swordman: true
    Locations:
      Right_Hand: true
    WeaponLevel: 3
    EquipLevelMin: 1
    Refineable: true
    Trade:
      Override: 100
      NoDrop: true
    Script: |
      bonus bUnbreakableWeapon; .@r = getrefine(); bonus bBaseAtk,(.@r/30)*30; if(.@r>=9){ .@i = 1; bonus3 bAutoSpellWhenHit,"BS_WEAPONPERFECT",1,10; } if(.@r>=6){ .@rate = 5*(.@i+1); bonus2 bAddClass,Class_All,5; }
``````
  * Result: 
  * Expected Result:  `.@r = getrefine(); bonus bBaseAtk,(.@r/3)*30; if(.@r>=9){ bonus3 bAutoSpell,"BS_WEAPONPERFECT",1,10; } if(.@r>=6){ bonus2 bAddClass,Class_All,5; }`
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:
