### ISSUE TITLE
update items Shooting_Star_C and F_Bow_Of_Rudra_C

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5597]
* **rAthena Hash**: 495769036aa3dbddf0c3a6fc8f611822b6064382

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: 
https://www.divine-pride.net/database/item/18100
``````
  - Id: 18100
    AegisName: Shooting_Star_C
    Name: Shooting Star
    Type: Weapon
    SubType: Bow
    Buy: 20
    Attack: 190
    Range: 5
    Jobs:
      BardDancer: true
      Hunter: true
    Locations:
      Both_Hand: true
    WeaponLevel: 4
    EquipLevelMin: 1
    Refineable: true
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      NoSell: true
      NoCart: true
      NoStorage: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      bonus bLongAtkRate,20;
``````
`remove Refineable: true`

https://www.divine-pride.net/database/item/18101
``````
  - Id: 18101
    AegisName: F_Bow_Of_Rudra_C
    Name: Rudra Bow
    Type: Weapon
    SubType: Bow
    Buy: 2
    Attack: 185
    Range: 5
    Jobs:
      Archer: true
      BardDancer: true
      Hunter: true
      Rogue: true
      Thief: true
    Locations:
      Both_Hand: true
    WeaponLevel: 4
    Script: |
      bonus bAtkEle,Ele_Holy; bonus bInt,5; skill "AL_CURE",1; skill "AL_HEAL",1; bonus2 bResEff,Eff_Poison,5000; bonus2 bResEff,Eff_Curse,5000; bonus2 bResEff,Eff_Silence,5000; bonus2 bResEff,Eff_Confusion,5000; bonus2 bResEff,Eff_Blind,5000;
``````
`remove job Thief: true`
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:
