### ISSUE TITLE
update item Catapult

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5602]
* **rAthena Hash**: 495769036aa3dbddf0c3a6fc8f611822b6064382

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: 
https://www.divine-pride.net/database/item/18109
``````
 - Id: 18109
    AegisName: Catapult
    Name: Thief Crossbow
    Type: Weapon
    SubType: Bow
    Buy: 56000
    Weight: 1100
    Attack: 150
    Range: 5
    Slots: 2
    Jobs:
      Rogue: true
    Classes:
      All_Third: true
    Locations:
      Both_Hand: true
    WeaponLevel: 4
    EquipLevelMin: 100
    Refineable: true
    Script: |
      .@r = getrefine(); bonus2 bSkillAtk,"SC_TRIANGLESHOT",(.@r*2); bonus2 bSkillUseSP,"SC_TRIANGLESHOT",(.@r*2);
``````
  * Result: `script now Decreases  edit to Increases`
  * Expected Result:  `.@r = getrefine(); bonus2 bSkillAtk,"SC_TRIANGLESHOT",(.@r*2); bonus2 bSkillUseSP,"SC_TRIANGLESHOT",-(.@r*2);`
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:
