### ISSUE TITLE
update items Malang_Snow_Crab and Brindle_Eel

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5603]
* **rAthena Hash**: 495769036aa3dbddf0c3a6fc8f611822b6064382

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: 
https://www.divine-pride.net/database/item/18107
``````
  - Id: 18107
    AegisName: Malang_Snow_Crab
    Name: Malangdo Crab
    Type: Weapon
    SubType: Bow
    Attack: 120
    Range: 5
    Jobs:
      Archer: true
      BardDancer: true
      Hunter: true
      Rogue: true
      Thief: true
    Locations:
      Both_Hand: true
    WeaponLevel: 1
    EquipLevelMin: 50
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      NoSell: true
      NoCart: true
      NoStorage: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      bonus bUnbreakableWeapon; bonus bLuk,3; bonus bCritAtkRate,50; if(BaseLevel>99) { bonus bLongAtkRate,10; }
``````
`update increases ranged attacks 10 to 20`
`bonus bUnbreakableWeapon; bonus bLuk,3; bonus bCritAtkRate,50; if(BaseLevel>99) { bonus bLongAtkRate,20; }
`
https://www.divine-pride.net/database/item/18108
``````
  - Id: 18108
    AegisName: Brindle_Eel
    Name: Zebra Eel
    Type: Weapon
    SubType: Bow
    Attack: 180
    Range: 5
    Jobs:
      BardDancer: true
      Hunter: true
    Locations:
      Both_Hand: true
    WeaponLevel: 1
    EquipLevelMin: 50
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      NoSell: true
      NoCart: true
      NoStorage: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      bonus bUnbreakableWeapon; bonus bAgi,3; autobonus "{ bonus bAspd,2; }",10,7000,BF_WEAPON,"{ specialeffect2 EF_HASTEUP; }"; if(BaseLevel>99) { bonus bLongAtkRate,10; }
``````
`update autobonus 7 sec to 5 sec  and Increases ranged attacks 10 to 20`
`bonus bUnbreakableWeapon; bonus bAgi,3; autobonus "{ bonus bAspd,2; }",10,5000,BF_WEAPON,"{ specialeffect2 EF_HASTEUP; }"; if(BaseLevel>99) { bonus bLongAtkRate,20; }`
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:
