### ISSUE TITLE
Mob DB Map Server Error

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5875]
* **rAthena Hash**: 7a1ea09  (normal/no issue on: 04d1f1f)

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  Map Server ERROR

```
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 206 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 208 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 210 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 212 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 214 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 216 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 219 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 258 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 260 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 262 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 264 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 267 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 310 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 313 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 350 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 352 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 354 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 356 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 358 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 360 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 363 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 407 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 409 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 412 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 489 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 491 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 493 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 495 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 497 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 499 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 502 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 545 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 547 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 550 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 621 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 623 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 625 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 627 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 629 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 632 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 676 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 678 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 681 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 756 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 758 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 761 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 764 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 806 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 809 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 847 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 849 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 851 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 853 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 855 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 857 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 860 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 863 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 900 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 902 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 904 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 906 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 908 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 910 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 913 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 916 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 960 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1004 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1041 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1043 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1045 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1047 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1049 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1051 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1054 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1057 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1100 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1102 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1105 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1108 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1186 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1188 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1190 and column 8.
(04/19/2021 08:37:05) [ Error ] : Maximum of 10 monster Drops met, skipping.
(04/19/2021 08:37:05) [ Error ] : Occurred in file '[1;37mdb/import/mob_db.yml[0m' on line 1192 and column 8.

```

  * Expected Result: No error like on hash: 04d1f1f
  * How to Reproduce:  Insert this to import/mob_db.yml

```
  - Id: 1207
    AegisName: STING
    Name: Sting
    Level: 104
    Hp: 10143
    BaseExp: 2172
    JobExp: 1629
    Attack: 794
    Attack2: 67
    Defense: 146
    MagicDefense: 34
    Str: 108
    Agi: 49
    Vit: 68
    Int: 34
    Dex: 99
    Luk: 24
    AttackRange: 1
    SkillRange: 10
    ChaseRange: 12
    Size: Medium
    Race: Formless
    Element: Earth
    ElementLevel: 3
    WalkSpeed: 300
    AttackDelay: 528
    AttackMotion: 500
    DamageMotion: 240
    Ai: 21
    Drops:
      - Item: Mud_Lump
        Rate: 4850
      - Item: Stone_Arrow
        Rate: 1500
      - Item: Glove_
        Rate: 1
      - Item: Coal
        Rate: 130
      - Item: Great_Nature
        Rate: 25
      - Item: Silk_Ribbon
        Rate: 10
      - Item: Explosive_Powder
        Rate: 800
      - Item: Fresh_G_Necklace
        Rate: 1
        StealProtected: true
      - Item: Sting_Card
        Rate: 1
        StealProtected: true
```

or this

```
  - Id: 3124
    AegisName: CHARLESTON3
    Name: Charleston 3
    Level: 145
    Hp: 23671401
    BaseExp: 3132000
    JobExp: 2473000
    Attack: 1500
    Attack2: 1000
    Defense: 200
    MagicDefense: 90
    Str: 208
    Agi: 106
    Vit: 205
    Int: 206
    Dex: 228
    Luk: 105
    AttackRange: 1
    SkillRange: 10
    ChaseRange: 12
    Size: Large
    Race: Demon
    Element: Neutral
    ElementLevel: 3
    WalkSpeed: 200
    AttackDelay: 676
    AttackMotion: 2016
    DamageMotion: 672
    Ai: 26
    Class: Boss
    Drops:
      - Item: Pilebuncker_P
        Rate: 20
      - Item: Tornado_Axe
        Rate: 20
      - Item: Robot's_Arm
        Rate: 10
      - Item: Giant_Blade
        Rate: 20
      - Item: Supplement_Part_Agi
        Rate: 40
      - Item: Upgrade_Part_Booster
        Rate: 40
      - Item: Charleston_Parts
        Rate: 250
```

  * Official Information: 
  

* **Modifications that may affect results**:
