### ISSUE TITLE
Inspiration Skill Duration and Cooldown

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5886]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/4a8be872150844e8c1acd2e1024d3f055d5a9fe9

* **Client Date**: 2020-06-20

* **Server Mode**: RE

* **Description of Issue**: 
Skill Inspiration has a much bigger CD than it should.

  * Result: 
  The Inspiration skill should have the same duration and cooldown as 3 minutes.
In this video of the current kRO, it shows at the very beginning the skill ends the effect and the player reuses right afterwards.
  * Expected Result: 
```
    Duration1:
      - Level: 1
        Time: 60000
      - Level: 2
        Time: 90000
      - Level: 3
        Time: 120000
      - Level: 4
        Time: 150000
      - Level: 5
        Time: 180000
    Cooldown:
      - Level: 1
        Time: 60000
      - Level: 2
        Time: 90000
      - Level: 3
        Time: 120000
      - Level: 4
        Time: 150000
      - Level: 5
        Time: 180000
```
  * How to Reproduce: 
  * Official Information: 
  [https://www.youtube.com/watch?v=msecSaUmv5o](url)
![image](https://user-images.githubusercontent.com/13624462/115779688-a8f14600-a38e-11eb-84bb-7a060ebf18c3.png)
  
  
  

* **Modifications that may affect results**:
