### ISSUE TITLE
getgroupitem doesn't stack items properly.

### ISSUE THREAD

**Issue by excelle** [rathena/rathena#6139]
* **rAthena Hash**: 789e8f7

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: getgroupitem doesn't stack items properly.
  * Result: 
  
![ROSlayers_0OH8m2TLsU](https://user-images.githubusercontent.com/7961300/126930820-b738eeea-a5f7-43ec-9a2b-502afd6f5123.png)

  * Expected Result: 
![ROSlayers_jQezkoD7Es](https://user-images.githubusercontent.com/7961300/126930880-db8a01b8-49bc-43f2-8184-544e5582f954.png)

  * How to Reproduce: Tested with item id 14003. Using the commented getitem script stacks the items properly.
  * Official Information: 
  

* **Modifications that may affect results**: none

**Comment by violent01** [comment]
try doing this @excelle 

`  - Id: 11503
    AegisName: Siege_White_Potion
    Name: WoE White Potion
    Type: Healing
    Weight: 100
    Stack:
      Amount: 30000
      Inventory: true
      Cart: true
      Storage: true
      GuildStorage: true
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      NoSell: true
      NoCart: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      itemheal rand(400,500),0;`

**Comment by violent01** [comment]
> try doing this @excelle
> 
> * Id: 11503
>   AegisName: Siege_White_Potion
>   Name: WoE White Potion
>   Type: Healing
>   Weight: 100
>   Stack:
>   Amount: 30000
>   Inventory: true
>   Cart: true
>   Storage: true
>   GuildStorage: true
>   Trade:
>   Override: 100
>   NoDrop: true
>   NoTrade: true
>   NoSell: true
>   NoCart: true
>   NoGuildStorage: true
>   NoMail: true
>   NoAuction: true
>   Script: |
>   itemheal rand(400,500),0;

Nah nevermind this Stack option doesn't work...

**Comment by idk-whoami** [comment]
remove  UniqueId: true
```
  - Group: ELITE_SIEGE_SUPPLY_BOX
    SubGroups:
      - SubGroup: 0
        List:
          - Item: Siege_White_Potion
            Amount: 100
            UniqueId: true
          - Item: Siege_Blue_Potion
            Amount: 50
            UniqueId: true
```
to

```
- Group: ELITE_SIEGE_SUPPLY_BOX
    SubGroups:
      - SubGroup: 0
        List:
          - Item: Siege_White_Potion
            Amount: 100
          - Item: Siege_Blue_Potion
            Amount: 50

**Comment by Atemo** [comment]
This is actually a thing

**Comment by mazvi** [comment]
@Atemo so if uniqueID true than stackable true? UniqueID will be same?

**Comment by Atemo** [comment]
The changes in the Pull Request are only about stackable items, equipments are not stackables.

With the pull request :
```
  - Group: XXXXXXXXXXXX
    SubGroups:
      - SubGroup: 0
        List:
          - Item: Siege_White_Potion
            Amount: 100
            UniqueId: true
```
^ Give 100 Siege_White_Potion with the same UniqueId, the 100 potions take 1 inventory slot only


```
  - Group: XXXXXXXXXXXX
    SubGroups:
      - SubGroup: 0
        List:
          - Item: Siege_White_Potion
            Amount: 100
            UniqueId: true
            Stacked: false
```
^ Give 100 Siege_White_Potion with the differents UniqueId, each potion takes 1 inventory slot
