### ISSUE TITLE
bonus5 bAutoSpellOnSkill cast skill incorrect lvl

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#6153]
rAthena Hash: 3d4021b
Client Date: 2020-09-02
Server Mode: RE
Description of Issue:

Result: 
This script bonus item is not working as it should, skill level used is random.
```
bonus5 bAutoSpellOnSkill,"CR_HOLYCROSS","LG_RAYOFGENESIS",10,1000,1;
```
Expected Result:
You should always use the skill "LG_RAYOFGENESIS" at level 10.

How to Reproduce:
Example:
```
  - Id: 5900
    AegisName: Divine_Guard_Hat
    Name: Divine Guard Hat
    Type: Armor
    Buy: 20
    Weight: 200
    Defense: 10
    Slots: 1
    Jobs:
      Crusader: true
    Classes:
      All_Third: true
    Locations:
      Head_Top: true
    EquipLevelMin: 100
    Refineable: true
    View: 1121
    Script: |
      .@r = getrefine(); .@level = getskilllv("LG_RAYOFGENESIS"); bonus5 bAutoSpellOnSkill,"CR_HOLYCROSS","LG_RAYOFGENESIS",10,1000,1;

```
Official Information:
Modifications that may affect results:
