### ISSUE TITLE
Quest Timelimit in X Days at 4AM

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6507]
* **rAthena Hash**: 
0d8118ceda8b223539be0443a7c5c7e3554832f7

* **Client Date**: 
2021-01-07aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Current time limit capabilities aren't sufficient to mimic the official quest behavior.

  * Expected Result:
  We need a possibility to set quests to a certain time after a certain amount of days.
  4AM, in 3 days for example.
 
  
  * How to Reproduce:
  I've tested with the following quest entry variants, then i used the setquest command to check the time in the quest UI.
```
  - Id: 1000
    Title: Transcend
    TimeLimit: 4h +2d
  - Id: 1001
    Title: Job Change to Acolyte
    TimeLimit: +2d 4h
```
Both 4h +2d and +2d 4h i tried to set it to 4AM in 3 days (testing if there's a way to do that). Just like many of the official quests are setup. However this doesn't work, as our current database doesn't seem to support such a setting.

  * Official Information:
  https://github.com/rathena/rathena/issues/6501

* **Modifications that may affect results**: 
Quest DB modification as stated in my test above.

**Comment by Tokeiburu** [comment]
The time displayed on the client is localized. That's normal.

**Comment by Everade** [comment]
Well that explains it.
Good to know, thanks 👍🏻

**Comment by aleDsz** [comment]
About having a possibility, I was thinking about the crontab time format, because you set it to each minute, daily, 2 weeks and much more possibilities with time, and it being parsed by a helper, can shows the time to run and how it should repeat

```yaml
  - Id: 1000
    Title: Transcend
    TimeLimit: 0 4 * * 0-6/2  # At 4AM each 2 days
  - Id: 1001
    Title: Job Change to Acolyte
    TimeLimit: 0 4 * * 0-6/2  # At 4AM each 2 days
```

[example sources](https://crontab.guru/)
