### ISSUE TITLE
Location: <map> to kill monster count doesn't work on instance maps on quest_db.yml

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#6628]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/6a25a392c21ec118e9a2512102f485453ee2083f

* **Client Date**: 20211103

* **Server Mode**: RE

* **Description of Issue**: 
When creating a quest ID with checking the monster count on an instance map, the count does not occur.
```
  - Id: 5912
    Title: "Joint Monster Hunting Request (1)"
    Targets:
      - Id: 1
        Location: 1@mjo2
        Count: 100
  ```      
        

  * Result: Killing the monster does not count.
  * Expected Result: Counting must occur even in instance map. Just like it works on normal maps.
  * How to Reproduce: 
  * Official Information: 

* **Modifications that may affect results**:
