### ISSUE TITLE
Need improvement on mob database related to MVP attribute Divine-Pride

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6680]
* **rAthena Hash**: Related to Renewal mob_db

* **Client Date**: -

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  NO MVP on rAthena
  * Expected Result:  MVP Attributes Like on Divine Pride
  * How to Reproduce: 
  * Official Information: 
  

On rAthena no MVP Attribute like below

https://raw.githubusercontent.com/rathena/rathena/master/db/re/mob_db.yml

```
  - Id: 3097
    AegisName: MM_MOROCC_ADT
    Name: Despair God Morroc
    Level: 175
    Hp: 120000000
    Attack: 5523
    Attack2: 175
    Defense: 203
    MagicDefense: 155
    Str: 122
    Agi: 103
    Vit: 12
    Int: 106
    Dex: 269
    Luk: 51
    AttackRange: 3
    SkillRange: 10
    ChaseRange: 12
    Size: Medium
    Race: Demon
    Element: Dark
    ElementLevel: 2
    WalkSpeed: 200
    AttackDelay: 750
    AttackMotion: 510
    DamageMotion: 500
    Ai: 10
    Class: Boss
    Drops:
      - Item: M_Morocc_Card
        Rate: 1
        StealProtected: true
```

Below list that requires the MVP attribute may include others mob I haven't mentioned:

![gambar](https://user-images.githubusercontent.com/8316103/158172814-8dcc1bd1-a411-4975-bd0b-c6c35a40031a.png)

https://www.divine-pride.net/database/monster/3091
https://www.divine-pride.net/database/monster/3092
https://www.divine-pride.net/database/monster/3097

https://www.divine-pride.net/database/monster/3421
https://www.divine-pride.net/database/monster/3422
https://www.divine-pride.net/database/monster/3423
https://www.divine-pride.net/database/monster/3424
https://www.divine-pride.net/database/monster/3425

Maybe others that I haven't met now, but the MVP attribute is on the monster page of divine pride like the example above. 

Maybe if there is synchronization DivinePride -> rA, it is necessary to check the attributes on the divine pride mob page. 

* **Modifications that may affect results**:
