### ISSUE TITLE
Equipment script can't work

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#6730]
* **rAthena Hash**: [6d0eef0](https://github.com/rathena/rathena/commit/6d0eef0a20811b6c60252689e5544f201039b349)
* **Client Date**: 2020-04-01
* **Server Mode**:  Pre-renewal
* **Description of Issue**:

**Comment by aleos89** [comment]
That's because you've ill-defined the scripts:
```yaml
    EquipScript: |
      setpcblock PCBLOCK_ATTACK|PCBLOCK_SKILL, true;
    UnequipScript: |
      setpcblock PCBLOCK_ATTACK|PCBLOCK_SKILL, false;
```
This works just fine for me!
