### ISSUE TITLE
Assumptio glow not getting removed on status change end

### ISSUE THREAD

**Issue by KrokusPokus** [rathena/rathena#6929]
* **rAthena Hash**:  9acb500
* **Client Date**:  2018-06-20eRagexeRE
* **Server Mode**:  Renewal

* **Description of Issue**:
The glow effect around the char does not get removed when the status change ends.
Possibly related to #1685

A possible fix is to change `EFST_ASSUMPTIO_BUFF` to `EFST_ASSUMPTIO2` in `db\re\status.yml`:

```
   - Status: Assumptio
    Icon: EFST_ASSUMPTIO_BUFF
    DurationLookup: HP_ASSUMPTIO
    CalcFlags:
      Def: true
    Opt3:
      Assumptio: true
    End:
      Kaite: true
```

There's also a second issue with the Assumptio glow not showing after logging in, even though the status change is still in effect from before logging out.
