### ISSUE TITLE
URGENT BUG ON BARTER SYSTEM (duplicate item)

### ISSUE THREAD

**Issue by samers1** [rathena/rathena#6985]
How to correct:
```
				// Required item not found
				if( j == MAX_INVENTORY ){
					return e_purchase_result::PURCHASE_FAIL_GOODS;
				}
			}else{
				for( int i = 0; i < requirement->amount; i++ ){
					int j;

					for( j = 0; j < MAX_INVENTORY; j++ ){
						if( sd.inventory.u.items_inventory[j].nameid == requirement->nameid ){
```
change 
				for( int i = 0; i < requirement->amount; i++ ){
to
				for( int i = 0; i < (requirement->amount * amount); i++ ){
				
-------------------------------------------------------------------

How to simulated the bug:
create this barter:
```yaml
  - Name: teste
    Map: prontera
    X: 150
    Y: 150
    Direction: Southwest
    Sprite: 4_F_SITDOWN
    Items:
      - Index: 0
        Item: Guarantee_Weapon_7Up
        RequiredItems:
          - Index: 0
            Item: Piece_Of_Angent_Skin
            Amount: 2
```
Use `@item Piece_Of_Angent_Skin 10`
try buy 5 ticket on barter.

The barter shop will consume only 2 skins instead of 10.

Resume:
You will paid two Piece_Of_Angent_Skin for 5 tickets.
