### ISSUE TITLE
Can't use Enchantgrade UI on Pre-renewal

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7062]
* **rAthena Hash**: 5e6fd03
* **Client Date**: 2021-11-16
* **Server Mode**: Pre-renewal
* **Description of Issue**: Can't use Enchantgrade UI
* **Modifications that may affect results**: 

**src\common\mmo.hpp**
```cpp
enum e_enchantgrade : uint16{
	ENCHANTGRADE_NONE = 0,
	ENCHANTGRADE_D,
	ENCHANTGRADE_C,
	ENCHANTGRADE_B,
	ENCHANTGRADE_A
};

#ifdef RENEWAL
	#define MAX_WEAPON_LEVEL 5
	#define MAX_ARMOR_LEVEL 2
	#define MAX_ENCHANTGRADE ENCHANTGRADE_A
#else
	#define MAX_WEAPON_LEVEL 4
	#define MAX_ARMOR_LEVEL 1
	#define MAX_ENCHANTGRADE ENCHANTGRADE_A
#endif
```

**db\enchantgrade.yml**
```yaml
Header:
  Type: ENCHANTGRADE_DB
  Version: 1

Footer:
  Imports:
  - Path: db/re/enchantgrade.yml
    Mode: Renewal
  - Path: db/pre-re/enchantgrade.yml
    Mode: Prerenewal
```

**db\pre-re\enchantgrade.yml**
```yaml
Header:
  Type: ENCHANTGRADE_DB
  Version: 1
  
Body:
  - Type: Armor
    Levels:
      - Level: 1
        Grades:
          - Grade: None
            Refine: 0
            Chance: 7000
            Bonus: 10
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 1
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Skyblue_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Skyblue_Jewel
                Amount: 5
                Zeny: 875000
          - Grade: D
            Refine: 0
            Chance: 6000
            Bonus: 30
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 3
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Topaz
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Topaz
                Amount: 5
                Zeny: 875000
          - Grade: C
            Refine: 0
            Chance: 5000
            Bonus: 50
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 5
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Violet_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Violet_Jewel
                Amount: 5
                Zeny: 875000
          - Grade: B
            Refine: 0
            Chance: 4000
            Bonus: 100
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 7
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Amber
                Amount: 2
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Amber
                Amount: 10
                Zeny: 875000
  - Type: Weapon
    Levels:
      - Level: 4
        Grades:
          - Grade: None
            Refine: 0
            Chance: 7000
            Bonus: 10
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 1
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Skyblue_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Skyblue_Jewel
                Amount: 5
                Zeny: 875000
          - Grade: D
            Refine: 0
            Chance: 6000
            Bonus: 30
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 3
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Topaz
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Topaz
                Amount: 5
                Zeny: 875000
          - Grade: C
            Refine: 0
            Chance: 5000
            Bonus: 50
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 5
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Violet_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Violet_Jewel
                Amount: 5
                Zeny: 875000
          - Grade: B
            Refine: 0
            Chance: 4000
            Bonus: 100
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 7
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Amber
                Amount: 2
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Amber
                Amount: 10
                Zeny: 875000
```
