### ISSUE TITLE
Instances with infinite keeping timer or idle timer instantly gets destroyed after creation.

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#7472]
### rAthena Hash

5549ad2

### Client Date

Irrelevant

### Server Mode

Renewal

### Result

1. Add an instance in instance_db.yml
```yml
  - Id: 100
    Name: Test
    TimeLimit: 0
    IdleTimeOut: 0
    Destroyable: false
    Enter:
      Map: izlude
      X: 100
      Y: 100
```
2. Create the instance via `instance_create("Test", IM_NONE)`
3. Watch the server console. The created instance will be destroyed in next tick.

My guess is that the db parser assigning INT64_MAX to instance time limits causes overflow when adding said limits with result from `gettick()` and makes the timer execute instantly.

### Relevant Log Output

```Shell
[Info]: [Instance] Created: Test (1)
[Info]: [Instance] Destroyed: Test (1)
```

### Expected Result

The instance should stay until explicitly destroyed via script command.

### How to Reproduce

Already described

### Official Information

N/A

### Modifications that may affect results

N/A
