### ISSUE TITLE
Possible wrong quest ID for Veins Field 04 Monster Society hunt-quest

### ISSUE THREAD

**Issue by eleriaqueen** [rathena/rathena#7504]
### rAthena Hash

5b8d0ee6a57236eaf103da587a2f9d965f4254c7

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

DB has quests 8677 for hunt-quest and 8676 for cooldown-quest but script juno_monster_society.txt tries to give quest 8675 for hunt-quest which does not exist.

Could be fixed by using ID 8675 instead of 8677 in quest_db

```
  - Id: 8676
    Title: "[Standby] Subjugation-Veins Field-3"
    TimeLimit: 4h
  - Id: 8677
    Title: "Subjugation-Veins Field-3"
    Targets:
      - Id: 1
        Count: 80
        Location: ve_fild04
        MapMobTargets:
          GALION: true
          DROSERA: true
          MUSCIPULAR: true```

```
```
switch( checkquest(8675,HUNTING) ) {
	case -1:
		mes "Or, if you are nearby, we also support teleportation service.";
		next;
		switch( select( "Listen to the situation", "Move to a nearby city", "Stop" ) ) {
		case 1:
			mes .@npc_name$;
			mes "Recently, the number of monsters is increasing in some areas, including around this area.";
			mes "I think the reason is that there are fewer people than before...";
			next;
			mes .@npc_name$;
			mes "It already means that you can't control the object naturally.";
			mes "To prevent further colonization from expanding, our Juno Monster Society has planned a massive subjugation.";
			next;
			mes .@npc_name$;
			mes "No matter how many adventurers visit, it's a big deal if you come down to where people live...";
			mes "So, can I ask you to subdue me?";
			next;
			mes .@npc_name$;
			mes "If you kill 80 monsters in this Veins Field, this field that I can see, our society will recognize your achievements and give you experience points.";
			next;
			if (select( "Accept", "Refuse" ) == 2) {
				mes .@npc_name$;
				mes "It's mutually beneficial, so why do you refuse...";
				close;
			}
			setquest 8675;
			mes .@npc_name$;
			mes "Good.";
			mes "I'll wait here.";
			close;
```

### Expected Result

I'd expect hunt-80-mobs quest to be added to the quest log.

### How to Reproduce

Go to ve_fild04 and try to accept Monster Society quest, it won't work.

### Official Information

Divine Pride has quest ID 8675 but not 8677 in its DB.
