### ISSUE TITLE
Item_cash.yml  dificulty to add itens

### ISSUE THREAD

**Issue by absint93** [rathena/rathena#7534]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

Giving some suggestions for implementing items in cash with more details in Yml... in the description of: how to add items in cash, this is VERY confusing. I've been trying to add items to the cash store for a few hours and I can't, it would be interesting to set an example to follow...

in the item_cash.yml description is just this:

###########################################################################
# - Tab                     Cash shop tab. Available tabs are New, Hot, Limited, Rental, Permanent, Scrolls, Consumables, Other, Sale.
#   Items:                  List of possible items.
#     - Item                Item name.
#       Price               Item cost in cash points (#CASHPOINTS).
###########################################################################

**Comment by Pokye** [comment]
It's very easy... here's an example of mine:
```
  - Tab: Consumables
    Items:
       # Diário de Aventuras
     - Item: Battle_Manual_X3
       Price: 300
       # Enciclopédia de Combate
     - Item: HE_Battle_Manual
       Price: 200
       # Manual de Combate de Classe
     - Item: Job_Manual50
       Price: 200
       # Medicina Milagrosa
     - Item: Miracle_Medicine
       Price: 500
       # Chicle de Bola
     - Item: HE_Bubble_Gum
       Price: 300
       # Goma de Mascar
     - Item: Bubble_Gum
       Price: 250
```
it is not mandatory to use the **# name of the item** ( I just wanted to detail it better so I can find the item later )
you must mention in ``- Tab:`` any of these ( **New, Hot, Limited, Rental, Permanent, Scrolls, Consumables, Other, Sale** ) to add the items in their respective tabs.
