### ISSUE TITLE
Grade enchant same grade different refine level.

### ISSUE THREAD

**Issue by mmo4th** [rathena/rathena#7607]
### rAthena Hash

da73084df50670337a8ecb9a7aa80bacbf87ccad

### Client Date

2023-01-05

### Server Mode

Renewal

### Result

1. In db/re/enchantgrade.yml ENCHANTGRADE_DB with following Body of 3x Grade: None but with different Refine requirement 9, 10, 11 as well as different Chance 1000, 2000, 7000.
```  - Type: Armor
    Levels:
      - Level: 2
        Grades:
          - Grade: None
            Refine: 9
            Chance: 1000
            Bonus: 10
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 1
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Skyblue_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Skyblue_Jewel
                Amount: 5
                Zeny: 875000
          - Grade: None
            Refine: 10
            Chance: 2000
            Bonus: 10
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 1
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Skyblue_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Skyblue_Jewel
                Amount: 5
                Zeny: 875000
          - Grade: None
            Refine: 11
            Chance: 7000
            Bonus: 10
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 1
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Skyblue_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Skyblue_Jewel
                Amount: 5
                Zeny: 875000
```
2. While in the game, the last read +11 is the only recognized by the enchant grade.
![rAGrade1](https://user-images.githubusercontent.com/105444810/218688841-4c664cbe-0c92-4891-99b3-de81be23580f.jpg)
![rAGrade2](https://user-images.githubusercontent.com/105444810/218688861-e2a36f05-4c76-4963-a2df-5fd0e96f8ef6.jpg)

### Expected Result

Allowing same Grade level but different refine and chance settings to be recognized.

### How to Reproduce

Setup the DB entries
Craft 2 level 2 armor with different refine level
then try ingame

### Official Information

kRO changed this last month
enabled grade enchant grade for Grade None +9 to D and Grade None +10 to D as well as previous Grade None +11 to  D
and then Grade D +10 or +11 to C .
With different normal chance / event chance
![rAGrade3](https://user-images.githubusercontent.com/105444810/218689570-ec0e8229-eb24-416c-aaa4-3e3c7ea0b3a0.png)

**Comment by datawulf** [comment]
My solution to this was a quite simple expand the chance field like this in my example here.
Not sure if devs would want this as a PR or have a more beautiful solution in mind. 

```
Header:
  Type: ENCHANTGRADE_DB
  Version: 2

Body:
  - Type: Armor
    Levels:
      - Level: 2
        Grades:
          - Grade: None
            Refine: 9
            Chance: 
              - Refine: 9
                Chance: 2000
              - Refine: 10
                Chance: 3000
              - Refine: 11
                Chance: 7000
              - Refine: 12
                Chance: 7000
              - Refine: 13
                Chance: 7000
              - Refine: 14
                Chance: 7000
              - Refine: 15
                Chance: 7000
              - Refine: 16
                Chance: 7000
              - Refine: 17
                Chance: 7000
              - Refine: 18
                Chance: 7000
              - Refine: 19
                Chance: 7000
              - Refine: 20
                Chance: 7000
            Bonus: 10
            Announce: false
            Catalyst:
                Item: Blessed_Etel_Dust
                AmountPerStep: 1
                MaximumSteps: 10
                ChanceIncrease: 100
            Options:
              - Option: 0
                Item: Etel_Skyblue_Jewel
                Amount: 1
                Zeny: 175000
                BreakingRate: 10000
              - Option: 1
                Item: Etel_Skyblue_Jewel
                Amount: 5
                Zeny: 875000
```
This would be the node parse code for "Chance"
```
			if( this->nodeExists( gradeNode, "Chance" ) ){
				uint16 chance,refineIndex;

				for( const ryml::NodeRef& chanceNode : gradeNode["Chance"] ){
					if( !this->asUInt16( chanceNode, "Refine", refineIndex ) ){
						return 0;
					}
					if( !this->asUInt16( chanceNode, "Chance", chance ) ){
						return 0;
					}
					grade->chance[refineIndex] = chance;
				}
			}
```
