### ISSUE TITLE
Checking Box VS Unbox Prices

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7801]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

To anticipate zeny abuse. It is necessary to check the price of the box and the price after unboxing.

Example this item:

```
  - Id: 12341
    AegisName: Special_Alloy_Trap_Box
    Name: Special Alloy Trap Box
    Type: Usable
    Buy: 30000
    Weight: 100
    Flags:
      BuyingStore: true
    Script: |
      getitem 7940,100;
```

The rathena system must check for usable items that have a getitem script. Then compare the purchase price when it is in box form, and the total selling price when the item is unboxed
