### ISSUE TITLE
Maximum ratio for MOB_ITEM_RATIO_DB problem

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#7835]
### rAthena Hash

https://github.com/rathena/rathena/commit/b6d6f09fd790eca05b428205a956fd15c47e795f

### Client Date

20180620

### Server Mode

Pre-Renewal

### Result

EXP Rate Conf : 
```
// The rate at which cards are dropped
item_rate_card: 900000
item_rate_card_boss: 700000
item_rate_card_mvp: 700000
item_drop_card_min: 1
item_drop_card_max: 10000
```

Example : 
```yaml
 - Item: Berzebub_Card
   Ratio: 65500
   List:
     BEELZEBUB_: true
 - Item: Kiel_Card
   Ratio: 400000
   List:
     KIEL_: true
```

### Expected Result

The rate should be depends on what we set at ratio

### How to Reproduce

`@mi` shows Berzebub_Card with ratio 65500 drop rate = 6.55% . This seems correct
`@mi` shows Kiel_Card with ratio 400000 but drop rate 0.67. This seems incorrect

### Official Information

None
