### ISSUE TITLE
opt1 statuses are canceled when a status change occurs

### ISSUE THREAD

**Issue by MrGrohminet** [rathena/rathena#8128]
### rAthena Hash

8be1f819d9997497bfab09234307c99f1ca56992

### Client Date

2018

### Server Mode

Pre-Renewal

### Result

op1 statuses are canceled when a status change occurs
[screen-capture_4.webm](https://github.com/rathena/rathena/assets/97130720/f1410237-7ede-4c24-a704-ade6401e1876)

### Expected Result

I dont know 

-> 1 : Opt1 status can be overrride (a stun can replace a freeze)
-> 2 : statuses cannot be overridden

### How to Reproduce

1/ Freeze a monster
2/ Use Lex  Divinia on it
-> The monster thaws and does not move

1/ Freeze a char (with ice cream)
2/ Use Angelus with party member
3/ You can't move (freeze cd), but you can use items

### Official Information

-

### Modifications that may affect results

src/map/status.cpp

`sc->opt1 = scdb->opt1;` will update and reset opt1 status.

Can be replaced by 

Result 1

```
	if (scdb->opt1 && !sc->opt1) {
		sc->opt1 = scdb->opt1;
	}
```

Or result 2

```
	if (scdb->opt1) {
		sc->opt1 = scdb->opt1;
	}
```

**Comment by Daraen1** [comment]
With my current rathena, I have the same issue (is older than yours).
I just tried your code just for testing. 
You cannot unfreeze a character by using Angelus skill for example but status on pvp mode still the same. 
I mean, you can unfreeze player with Stun skill like Scream. 
Probably better for me to post a video to explain correctly...

**Comment by Salfer13** [comment]
![image](https://github.com/rathena/rathena/assets/52106036/a12fe41e-bbb6-460b-8ab9-effc518bc6ad)
 
 if I assign opt2 status to any opt1 status, opt1's effect will be interrupted, it will work but will not be displayed (potions can still be used)
[2024-03-12_00-15-39.webm](https://github.com/rathena/rathena/assets/52106036/bbf6d005-e717-473b-8e60-26334a355c52)

**Comment by Daraen1** [comment]
I can confirm for potion thingy.
With @Singe-Horizontal , we have seen in /(pre-)re/status.yml missing some status flags.
For example, freeze and sleep for stun status.
*We just check the initial problem described by the author. It could be missed other failed status for stun*

```   
- Status: Stun
    DurationLookup: NPC_STUNATTACK
    States:
      NoMove: true
      NoCast: true
      NoAttack: true
    Opt1: Stun
    Flags:
      SendOption: true
      BossResist: true
      StopAttacking: true
      StopCasting: true
    Fail:
      Refresh: true
      Inspiration: true
      Gvg_Stun: true
      Stun: true
      Freeze: true
      Sleep: true
 ```
