### ISSUE TITLE
Enchant Deadly Poison / Magnum Break Damage Bonus and Durations

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#8187]
### rAthena Hash

42bd87d

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

In pre-renewal, Enchant Deadly Poison is missing the additional 25% Poison damage effect (same as Magnum Break except it is 25% instead of 20% and POISON instead of FIRE).
In renewal, the additional damage is working, but the duration is off (using Duration2 which is reserved for DPOISON duration instead of using Duration1).

### Expected Result

In both pre-renewal and renewal Enchant Deadly Poison applies an additional 25% Poison damage effect for the duration of EDP (same effect as Magnum Break, but beware that the effect in rAthena is different for each).

### How to Reproduce

I found this by searching for occurrences of ASC_EDP in the source code.

### Official Information

https://ro.kokotewa.com/db/skl_info?id=ASC_EDP

**Comment by Playtester** [comment]
```
		case SC_SUB_WEAPONPROPERTY:
			if (sd && val3 == ASC_EDP) {
				uint16 poison_level = pc_checkskill(sd, GC_RESEARCHNEWPOISON);

				if (poison_level > 0) {
					tick += 30000; // Base of 30 seconds
					tick += poison_level * 15 * 1000; // Additional 15 seconds per level
				}
			}
			break;
```
There's actually some cute that overwrites the duration.

This might need some more tests to verify.

**Comment by Playtester** [comment]
```
  - Id: 378
    Name: ASC_EDP
    Description: Enchant Deadly Poison
    MaxLevel: 5
    Type: Weapon
    TargetType: Self
    DamageFlags:
      NoDamage: true
    Hit: Single
    HitCount: 1
    Element: Poison
    Duration1:
      - Level: 1
        Time: 40000
      - Level: 2
        Time: 45000
      - Level: 3
        Time: 50000
      - Level: 4
        Time: 55000
      - Level: 5
        Time: 120000
```
Duration for EDP in renewal is strangely defined I assume it should be 40000, 60000, 80000, 100000, 120000.
