### ISSUE TITLE
NoChat Status on Berserk

### ISSUE THREAD

**Issue by AsuraPlop** [rathena/rathena#8247]
### rAthena Hash

https://github.com/rathena/rathena/commit/9eff7be9cdc90940fbe119ce302ea5e4b3f49623

### Client Date

20180620

### Server Mode

Pre-Renewal

### Result

  There is no effect when modifying the NoChat setting in Frenzy (Berserk)/ status.yml.
  
  
  ```
- Status: Berserk
    Icon: EFST_BERSERK
    DurationLookup: LK_BERSERK
    States:
      NoCast: true
      NoChat: true
      NoEquipItem: true
      NoUnEquipItem: true
      NoConsumeItem: true
    CalcFlags:
      Def: true
      Def2: true
      Mdef: true
      MDef2: true
      Flee: true
      Speed: true
      Aspd: true
      MaxHp: true
      Regen: true
    Opt3:
      Berserk: true
    Flags:
      NoSave: true
    Fail:
      Saturdaynightfever: true
      _Bloodylust: true
```

### Expected Result

The chat should be enabled while using Frenzy.

### How to Reproduce

Delete, comment out, or set to false the 'NoChat' state.

### Official Information

...
