### ISSUE TITLE
attackspeed on Hunter using daggers is wrong (prerenewal)

### ISSUE THREAD

**Issue by DrummerBoy33** [rathena/rathena#8282]
### rAthena Hash

2963e52

### Client Date

2024-04-25

### Server Mode

Pre-Renewal

### Result

Weapon delay value is wrong for hunters when using daggers. In job_db1.txt it says 600 for both daggers and bows, but the value for daggers should be 575 (source: https://irowiki.org/classic/ASPD and https://rocalc.com/)

### Expected Result

Weapon delay value for Hunter using dagger-type weapon should be 575 in job_db1.txt

### How to Reproduce

n/a

### Official Information

the table at https://irowiki.org/classic/ASPD and calculator input at https://rocalc.com/ show the lower value of 575

**Comment by aleos89** [comment]
You state job_db1.txt, but we don't use that database anymore. All ASPD are stored in job_aspd.yml files. Also, iRO is well known to differ vastly versus kRO so it's not a great source for comparing data.

**Comment by Playtester** [comment]
Easy to check...
```
  - Jobs:
      Hunter: true
      Sniper: true
      Baby_Hunter: true
    BaseASPD:
      Fist: 400
      Dagger: 600
      Bow: 600
```

Sniper 94/69 all stats 1 (except Job Bonus and Owl's Eye 10): 144 ASPD
Raising DEX to 99 -> 150 ASPD

ASPD perfectly matches between official servers and rAthena already, so I will consider this report invalid.
