### ISSUE TITLE
Usable Items are not working

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#8423]
### rAthena Hash

latest

### Client Date

20220406

### Server Mode

Renewal

### Result

Item function:
```
function	script	NTB	{
    .@ritem = F_Rand(5909,5911,5913,5915,18740,19015,19158,19500,19507,19508,19509,19510,19511,19512,19513,19514,19515,19516,19517,19518,19519,19520,19521,19522,19524,19525,19526,19527,19528,19529,19530,19531,19532,19533,19534,19535,19536,19537,19538,19539,19540,19541,19579);
    getitem .@ritem, 1;
    announce "["+strcharinfo(0)+"] get a ["+getitemname(.@ritem)+"] from Asuriel Treasure Box.",0;
    end;
}
```
Custom item:
```
  - Id: 50005
    AegisName: AsurielRO Treasure Box
    Name: Asuriel Treasure Box
    Type: Cash
    Buy: 20
    Weight: 10
    Trade:
      NoDrop: true
      NoSell: true
      NoCart: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      callfunc "NTB";
```

When you try to click the item it is not consuming, also other (default) usable items are not working when you click it.

### Expected Result

---

### How to Reproduce

---

### Official Information

---
