### ISSUE TITLE
All_Upper cannot wear by 4th classes

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#8616]
### rAthena Hash

a687ddeb854de4c9207d21dfbaab7f6b83944165

### Client Date

20220602

### Server Mode

Renewal

### Result

Try equip item 400489 with Dragon Knight Max Level.

### Expected Result

Able to equip item 400489 on Dragon Knight Max Level.

### How to Reproduce

@ item 400489
@ job 4252
@ lvup 999

### Official Information

-

**Comment by Lemongrass3110** [comment]
No the problem is that those items are missing the 2nd class entries.
It has to look like this:
```yml
    Jobs:
      Swordman: true
      Knight: true
      Crusader: true
    Classes:
      All_Upper: true
```
