### ISSUE TITLE
bonus2 bAddMonsterDropItemGroup didn't drop item

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#8896]
### rAthena Hash

ee8f181dd9b73d9d69002f19c101d747f4ceaae2

### Client Date

20220602

### Server Mode

Renewal

### Result

Drop bonus by item group didn't dropping.

### Expected Result

Item drop from drop item group bonus

### How to Reproduce

@ item 1142 then go killing monster.

### Official Information

Not sure.

**Comment by Playtester** [comment]
The functionality was updated to official recently. Make sure you have updated the item script to have 10000 activation rate.
```
  - Id: 1142
    AegisName: Jewel_Sword
    Name: Jeweled Sword
    Type: Weapon
    SubType: 1hSword
    Buy: 20
    Weight: 2200
    Attack: 104
    Range: 1
    Jobs:
      Alchemist: true
      Assassin: true
      Blacksmith: true
      Crusader: true
      Knight: true
      Merchant: true
      Rogue: true
      Swordman: true
      Thief: true
    Locations:
      Right_Hand: true
    WeaponLevel: 3
    EquipLevelMin: 68
    Refineable: true
    Script: |
      bonus2 bAddMonsterDropItemGroup,IG_Jewel,10000;
```
If you want to customize the drop rates, do that in item_group_db instead. And make sure that's also updated.
```
  - Group: JEWEL
    SubGroups:
      - SubGroup: 1
        List:
          - Index: 0
            Item: Yellow_Gemstone
            Rate: 100
          - Index: 1
            Item: Red_Gemstone
            Rate: 100
          - Index: 2
            Item: Blue_Gemstone
            Rate: 100
          - Index: 3
            Item: Dark_Red_Jewel
            Rate: 10
          - Index: 4
            Item: Violet_Jewel
            Rate: 10
          - Index: 5
            Item: Skyblue_Jewel
            Rate: 10
          - Index: 6
            Item: Azure_Jewel
            Rate: 10
          - Index: 7
            Item: Scarlet_Jewel
            Rate: 10
          - Index: 8
            Item: Cardinal_Jewel
            Rate: 10
          - Index: 9
            Item: Cardinal_Jewel_
            Rate: 10
          - Index: 10
            Item: Red_Jewel
            Rate: 10
          - Index: 11
            Item: Blue_Jewel
            Rate: 10
          - Index: 12
            Item: White_Jewel
            Rate: 10
          - Index: 13
            Item: Golden_Jewel
            Rate: 10
          - Index: 14
            Item: Bluish_Green_Jewel
            Rate: 10
          - Index: 15
            Item: Crystal_Jewel
            Rate: 5
          - Index: 16
            Item: Crystal_Jewel_
            Rate: 4
          - Index: 17
            Item: Crystal_Jewel__
            Rate: 3
          - Index: 18
            Item: Crystal_Jewel___
            Rate: 2
          - Index: 19
            Item: Glass_Bead
            Rate: 50
```
Should look like this. Make sure the SubGroup is 1.
