### ISSUE TITLE
Use command by function not work.

### ISSUE THREAD

**Issue by Beginerxxxxx** [rathena/rathena#8897]
### rAthena Hash

https://github.com/rathena/rathena/commits/master

### Client Date

20230906

### Server Mode

Renewal

### Result

Hello everyone,
I encountered an additional issue: using the command "atcommand" and "soundeffectall"  under the command "function" doesn’t work.
Normally, it should function properly. Please help check this issue. Thank you very much!

```
function	script	test	{
atcommand "@heal";
}
```

```
function	script	test_sound	{
soundeffectall "sound.wav",0;
}
```

```
  - Id: 10
    AegisName: "Test"
    Name: "Test"
    Type: Healing
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      TradePartner: true
      NoSell: true
      NoCart: true
      NoStorage: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Buy: 20
    Weight: 10
    Script: |
      callfunc "test";
```

```
  - Id: 11
    AegisName: Test_sound
    Name: Test sound
    Type: Armor
    Locations:
      Costume_Head_Mid: true
    ArmorLevel: 2
    Refineable: true
    Gradable: true
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      TradePartner: true
      NoSell: true
      NoCart: true
      NoStorage: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Weight: 0
    Refineable: true
    Gradable: true
    EquipLevelMin: 20
    View: 2595
    Script: |
    EquipScript: |
      callfunc "test_sound",2;
    UnEquipScript: |
      callfunc "test_sound",2;
```

### Relevant Log Output

```Shell
none
```

### Expected Result

none

### How to Reproduce

none

### Official Information

none

### Modifications that may affect results

none
